testKeys/src/main/java/vippsKeys/HttpRequest.java
testKeys/src/main/java/vippsKeys/HttpResponse.java
testKeys/src/main/java/vippsKeys/KeysContainerJSON.java
testKeys/src/main/java/vippsKeys/VIPPS_APIKeys.java
testKeys/src/main/java/vippsKeys/VIPPS_AccessTokenJSON.java
testKeys/src/main/java/vippsKeys/VIPPS_CustomerInfoJSON.java
testKeys/src/main/java/vippsKeys/VIPPS_InitiatePaymentJSON.java
testKeys/src/main/java/vippsKeys/VIPPS_InitiatePaymentRequest.java
testKeys/src/main/java/vippsKeys/VIPPS_InitiatePaymentResponseJSON.java
testKeys/src/main/java/vippsKeys/VIPPS_MerchantInfoJSON.java
testKeys/src/main/java/vippsKeys/VIPPS_TransactionJSON.java
testKeys/src/main/java/vippsKeys/VIPPS_WebPageButtonClicker.java
testKeys/src/main/java/vippsKeys/VIPPS_getAccessToken.java
testKeys/src/main/java/vippsKeys/getAccessTokenAndInitiatePayment.java
testKeys/src/test/java/vippsKeys/testInputJson.java

All .java files formatted with https://github.com/google/google-java-format:
```
$ brew install google-java-format
$ find . -name \*java -type f | xargs google-java-format -r
```

Google Java formatting

---

README.md

Editor decided to trim some end-line-whitespace as well it seems, oh well.

Document current working MT versions for Android

---

code-examples/ecom_python_example/app.py

default it to 8080 port for local dev.

app.run(host='0.0.0.0' port=8080) 

---

settlements/sftp-report-service/README.md

Added info about username for SFTP access

Added info about username for SFTP access

---

vipps-test-environment.md

According to the [September newsletter for developers](https://github.com/vippsas/vipps-developers/blob/master/newsletters/2021-09-newsletter.md#api-dashboard-for-the-test-environment), you have launched API Dashboard in the test environment

API Dashboard is available for test environment

---

newsletters/2021-12-newsletter.md

Note about Short URL QR API can deliver for use in creating QR code

Added line about QR short url

---

README.md
contact.md
housekeeping/README-template.md
newsletters/2019-11-newsletter.md
newsletters/2022-04-newsletter.md
postman-guide.md
settlements/README.md
settlements/csv/README.md
settlements/sftp-report-service/README.md
testdata/README.md
vipps-api-lifecycle.md
vipps-developer-portal-getting-started.md
vipps-getting-started.md
vipps-test-environment.md

And fix small spelling (can not => cannot)

Remove markdown violations

---

postman-guide.md

Remove all the space in the table (I added that).

Change links to API guides and postman guides

---

tools/vipps-api-global-postman-environment.json

Also added in the eCom collection: https://github.com/vippsas/vipps-ecom-api/commit/19b48c147a8c45443cec9df7c377852b85be6ab6
Straight to master! 🙈

Added: useExplicitCheckoutFlow

---

common-topics/userinfo.md

Userinfo tweaks

---

common-topics/errors.md

Instead of referring to https://opensource.zalando.com/problem/constraint-violation/

Added API error page

---

common-topics/errors.md

From https://github.com/vippsas/webhooks/pull/215/files

RFC7807: Added 'status'

---

common-topics/vipps-landing-page.md

Sequence diagram: [Here](https://mermaid.live/edit#pako:eNqlU01rwzAM_SvCl11Seg-jMLbLoBmBkh1GLm6iNqbxx2yHUkr_-6TG_diynaYcguOn96QX6Sga26LIRcDPAU2DL0puvdS1AQonfVSNctJEKEAGKNA3HZ2m10_lKwPelXOBD1PEsmTAUppWmS3dbPEXFuduLNK5ESGbaD1UfFMF9OPHYjZbLEgoh1ejopIRiemg0cTHtZ8v9ip2QFn8tkOEsFMuaZdXadlHeLNeyx42vd3nP1FgLGU6bNRGYTvmcJAsqy_LHFad3UPsEPpJYxzVBfdszUZ5Paf60M_ZRKJ3nTUkMuj1pSuOZXltrZwA0KQ6Ug3kGMGG0IHGEEg7h1qUoxHg-aeGWIsxpbompGrCxbJE6dxNOVE0IxK_qxZ_Av5paXXnqE7D9hCokTAQ8c1b7APeU7tz59EPd96ndqpJrTIqa0AZnjCwpj_cWcsPH0QmSF9L1dJyHPlbLagojbVgh1vpd2zriXByiHZ1MI3IWT8Tg2tpGtMiiXwjqdZMYKtoiotx285Llwma-Q9rL5jTF1dCKd4)

SLP clarification

---

newsletters/2023-03-newsletter.md

Work in progress. Making is as short and non-marketing-like as possible.

Newsletter: Simplify, simplify

---

test-environment.md

Adding details to partner access to portal.

Tweaking partner access info

---

common-topics/README.md
common-topics/direct-vs-psp.md
faqs/other-faq.md

See Slack: https://vippsas.slack.com/archives/CLAH8P89M/p1679728965563959
If we go for this:
- Replace the text here with a link to this "Common topic": https://developer.vippsmobilepay.com/docs/vipps-developers/faqs/other-faq#what-functionality-is-included-in-the-ecom-api-but-not-the-psp-api
- Fix the link in the PSP FAQ: https://developer.vippsmobilepay.com/docs/APIs/psp-api/vipps-psp-api-faq#what-functionality-is-included-in-the-ecom-api-but-not-the-psp-api

Direct vs PSP

---

newsletters/2023-03-newsletter.md

Highlighting "Subscribe", and some other adjustments.

Making it sparkle ✨

---

contact.md

Changed from integration@vipps.no to developer@vippsmobilepay.com

Changed contact email

---

quick-start-guides.md

Formatting fixes

---

common-topics/cancel.md
common-topics/direct-vs-psp.md
common-topics/reserve-and-capture.md
common-topics/vipps-landing-page.md
contact.md
developer-resources/portal.md
faqs/other-faq.md
faqs/problems-for-end-users-faq.md
faqs/refunds-faq.md
getting-started.md

Required to avoid broken links when doing changes to the docusaurus build.

CI-2189: Link to markdown files

---

common-topics/vipps-landing-page.md
faqs/vipps-landing-page-faq.md

Background: https://vippsas.slack.com/archives/C9KA4EN1Y/p1682507035820209

Landing page details

---

common-topics/refund.md

Refund clarification

---

faqs/users-and-payments-faq.md

Added FSCP

---

faqs/common-problems-faq.md

FSCP info, clarifications, links

---

common-topics/direct-vs-psp.md
faqs/users-and-payments-faq.md

An update after discussion about benefits of direct over PSP. Hope it makes it clearer.

Clarified benefits of direct vs PSP

---

common-topics/orderid.md
common-topics/transactiontext.md

Now using the ePayment API as default, and mentioning that it supersedes the eCom API.

Update for ePayment (not just eCom)

---

test-environment.md

Super simple note that mt test users can be found in the merchant portal.
Making this better shouldn't be hard 😅 but it's a start... maybe..

simple notice about the mt users in merchantPortal

---

mp-migration-guide/pos.md

Detailing how best to migrate to the Common platfrom if you are a MobilePay PoS merchant today.

Wrote PoS migration guide

---

newsletters/2023-10-newsletter.md

Pretty-print: https://github.com/vippsas/vipps-developers/blob/ccf9ae505b882435ad7e3e4b6fbae8dff4b610cd/newsletters/2023-10-newsletter.md

Newsletter 2023-10

---

settlements/README.md
settlements/sftp-report-service/README.md

https://vippsas.slack.com/archives/CNEJMB7GT/p1696936123759259

SFTP deprecation notice

---

newsletters/2023-10-newsletter.md
settlements/README.md
settlements/pdf/README.md
settlements/sftp-report-service/README.md

Emphasize deprecation of sftp even more.
